### ISSUE TITLE
NoSuchMethodError after update to 0.5.0

### ISSUE THREAD

**Issue by PabloPL** [letsar/flutter_slidable#71]
I'm getting following error after update to 0.5.0 version

>I/flutter (21118): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21118): The following NoSuchMethodError was thrown building Slidable(dirty, dependencies:
I/flutter (21118): [_ScrollableScope], state: SlidableState#1c8cb(tickers: tracking 1 ticker)):
I/flutter (21118): The method '[]' was called on null.
I/flutter (21118): Receiver: null
I/flutter (21118): Tried calling: [](Instance of 'SlideActionType')
I/flutter (21118):
I/flutter (21118): When the exception was thrown, this was the stack:
I/flutter (21118): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:50:5)
I/flutter (21118): #1      SlidableState._dismissThreshold
package:flutter_slidable/…/widgets/slidable.dart:562
I/flutter (21118): #2      SlidableState.build
package:flutter_slidable/…/widgets/slidable.dart:897
I/flutter (21118): #3      StatefulElement.build 
package:flutter/…/widgets/framework.dart:3825
I/flutter (21118): #4      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3739

`widget.dismissal` is null in _dismissThreshold

Adding some dummy check for null value in dismissal solves error (no idea why ?? operator is not working when ?. returns null...)

**Comment by tegab** [comment]
can you show code on how you solved it.. thnx

**Comment by PabloPL** [comment]
In slidable.dart (in flutter_slidable lib) replace 
```
double get _dismissThreshold =>
    widget.dismissal?.dismissThresholds[actionType] ?? _kDismissThreshold;
```
With something like this
```
double get _dismissThreshold {
    if (widget.dismissal == null) return _kDismissThreshold;
    else return widget.dismissal.dismissThresholds[actionType] ?? _kDismissThreshold;
  }
```
For me it's working fine

**Comment by jaumard** [comment]
I can confirm the problem (and the solution ^^) would be nice to have this patch and deploy @letsar :)

**Comment by jeffaknine** [comment]
First time trying the package and I'm running into this issue as well. @PabloPL maybe you could send a PR to get this fixed ?

**Comment by PabloPL** [comment]
PR created.

**Comment by Nothing-Works** [comment]
have the same problem, hopefully, the PR can be merged ASAP.....

**Comment by HiroshiHorie** [comment]
Please fix ASAP!

**Comment by eponcedeleon** [comment]
Until we have this PR merged, I am using a workaround, set dismissal to the following:
```
dismissal: SlidableDismissal(
     child: SlidableDrawerDismissal(),
     onWillDismiss: (actionType) {
         return false;
     },
),
```
this is enforcing to have a dismissal property by always is canceling the dismissal actions

**Comment by JeffersonCarvalh0** [comment]
Thanks, @eponcedeleon. Your solution worked here, but I had to add a `key` property to the`Slidable` object in order for it to work

**Comment by letsar** [comment]
Fixed in 0.5.2
